# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    PLATFORMIO_CI_SRC: CoffeemakerPS

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'

- script: |
    echo installing platform.io
    python -m pip install --upgrade pip setuptools wheel platformio
    platformio update
  displayName: 'Install platform.io'

- script: |
    echo build project
    echo PLATFORMIO_CI_SRC: $(PLATFORMIO_CI_SRC)
    platformio ci --project-conf=CoffeemakerPS/platformio.ini --lib="." --lib="CoffeemakerPS/lib/AWS_IOT" --lib="CoffeemakerPS/lib/aws-mqtt-websockets" --lib="CoffeemakerPS/lib/aws-sdk-arduino-esp8266" --lib="CoffeemakerPS/lib/PubSubClient" --lib="CoffeemakerPS/lib/Syslog"
  displayName: 'build platform.io project'
