# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    PLATFORMIO_CI_SRC: CoffeemakerPS/src

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'

- script: |
    echo installing platform.io
    python -m pip install --upgrade pip setuptools wheel platformio
    platformio update
  displayName: 'Install platform.io'

- script: |
    echo installing platform.io libraries 
    platformio lib -g install \ 
      "Adafruit GFX Library" \ 
      "Adafruit PN532" \
      "Adafruit ST7735 and ST7789 Library" \
      "ArduinoJson-esphomelib" \
      "Brzo I2C" \ 
      "ESP32httpUpdate" \
      "ESP8266 and ESP32 OLED driver for SSD1306 displays" \
      "IFTTTWebhook" \
      "MFRC522" \
      "Paho" \
      "Time" \
      "U8g2" \
      "Ucglib" \
      "WebSockets" \
      "mbedtls"
  displayName: 'Install platform.io libraries'

- script: |
    echo build project
    echo PLATFORMIO_CI_SRC: $(PLATFORMIO_CI_SRC)
    platformio ci --project-conf=CoffeemakerPS/platformio.ini
  displayName: 'build platform.io project'
